site_name: McGill NLP Project Documentation
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  logo: assets/logo-inverse.png
  favicon: assets/favicon.png
  features:
    - header.autohide

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/McGill_NLP
    - icon: fontawesome/brands/github
      link: https://github.com/McGill-NLP/
  homepage: https://mcgill-nlp.github.io

extra_css:
  - stylesheets/extra.css

# See: https://squidfunk.github.io/mkdocs-material/reference/code-blocks/
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

copyright: Copyright &copy; 2022 McGill NLP